### ISSUE TITLE
Maintenance branches for firmware-utils

### ISSUE THREAD

**Issue by jwmullally** [openwrt/firmware-utils#18]
This change introduces stable API versioning for <https://git.openwrt.org/project/firmware-utils.git> matching the OpenWrt release branches (`openwrt-22.03`, `openwrt-23.05`), similar to <https://git.openwrt.org/project/luci.git>.

This makes it much much easier and more sustainable for contributors and maintainers to use GIT to manage new device support and bugfixes for previous releases, without breaking any APIs. For example, using `git cherry-pick` to get new changes from `/master` while removing any API differences. Currently, new device support and bugfixes must be managed downstream manually as patches against an old git ref (e.g. [this patch](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=a507243bfeb1597bb78a5e5e8101022e6aca0836)). Other projects using firmware-utils will also benefit from this stable versioning scheme, even if they don't follow OpenWrt's version scheme, but they will still be free to continue using fixed git refs and downstream patches as before.

This only involves `/openwrt-22.03` and `/openwrt-23.05`, as firmware-utils was still in-tree during OpenWrt `/openwrt-21.02`.

[See previous discussion and developer approval](https://github.com/openwrt/firmware-utils/pull/9#issuecomment-1590565448). As this requires a good few commits and branches to be created, it is easier to just recommend in this issue the steps for a project developer to do than to submit 10 different PRs. If the safe **Option A)** is chosen below, it will have no functional impact on current releases and should be safe to implement right away.

## Step 1: Create firmware-utils release branches matching existing OpenWrt release branches.

This will only create new branches, so can be done any time with no impact on external consumers. Later, changes can be added to each firmware-utils release branch independantly and the PKG_SOURCE_VERSION updated in `openwrt.git/tools/firmware-utils/Makefile` on each OpenWrt release branch.

```
cd ~/src/firmware-utils

# https://git.openwrt.org/?p=openwrt/openwrt.git;a=history;f=tools/firmware-utils/Makefile;hb=refs/heads/openwrt-22.03
# https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=9c2ed54aa2fefeb88dd06d1f393a70ab7d48f24f
git branch openwrt-22.03 ddc3e00e314d3fbc3f9faab2d07395722ce9b01a
git push origin -u openwrt-22.03

# https://git.openwrt.org/?p=openwrt/openwrt.git;a=history;f=tools/firmware-utils/Makefile;hb=refs/heads/openwrt-23.05
# https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=2cece6e2b078e6acb97f3ed99ffc58f0f8fa2365
git branch openwrt-23.05 9e2de8515be15e2b61ae518ce592e5b446ef2d48
git push origin -u openwrt-23.05
```

## Step 2: Sync release branches

EITHER:

### Option A) Conservatively just replace existing out-of-tree patches in OpenWrt with updated firmware-utils commit refs

This preserves the current code and behaviour of all the versions, and should have zero impact.

```
cd ~/src/firmware-utils

git checkout openwrt-22.03
git cherry-pick a2c80c586b81efc1662fec23202b88e2790e305e
git cherry-pick affc38e89b3544edc97d05367f8aeafa4c4e73bd

git checkout master
# Import patch from https://git.openwrt.org/?p=openwrt/openwrt.git;a=blob;f=tools/firmware-utils/patches/001-add-sifiveu-guid-types.patch;h=45900e982c9c4ccffb8531d70c18151a47ccbbe9;hb=18238c442866a6ae93533e2421a6f44bc9e57ac6

git checkout openwrt-23.05
git cherry-pick $(git rev-parse master)
```

OR:

### Option B) Update current firmware-utils release branches to latest code

Looking at the differences between the current [openwrt-22.03 commit and master](https://github.com/openwrt/firmware-utils/compare/ddc3e00e314d3fbc3f9faab2d07395722ce9b01a..d16ff798d58a508e7422322be2bd25d38224018e) and [openwrt-23.05 and master](https://github.com/openwrt/firmware-utils/compare/9e2de8515be15e2b61ae518ce592e5b446ef2d48..d16ff798d58a508e7422322be2bd25d38224018e), it seems purely additive and there doesn't appear to be any backwards incompatible changes, so now might be a good time to just bring both current release branches up to date.

This will require a review by the firmware-utils maintainers but I would be in favor of it.

```
# Diff from OpenWrt 22.03 firmware-utils to current master
git diff ddc3e00e314d3fbc3f9faab2d07395722ce9b01a d16ff798d58a508e7422322be2bd25d38224018e
# Diff from OpenWrt 23.05 firmware-utils to current master
git diff 9e2de8515be15e2b61ae518ce592e5b446ef2d48 d16ff798d58a508e7422322be2bd25d38224018e
```

```
cd ~/src/firmware-utils

git checkout master
# Import patch from https://git.openwrt.org/?p=openwrt/openwrt.git;a=blob;f=tools/firmware-utils/patches/001-add-sifiveu-guid-types.patch;h=45900e982c9c4ccffb8531d70c18151a47ccbbe9;hb=18238c442866a6ae93533e2421a6f44bc9e57ac6

git checkout openwrt-22.03
git merge --ff-only master

git checkout openwrt-23.05
git merge --ff-only master
```

# Step 3: Update OpenWrt firmware-utils package with commit refs from Step 2
```
cd ~/src/openwrt

git checkout openwrt-22.03
git rm tools/firmware-utils/patches/001-tplink-safeloader-add-Archer-AX23.patch
git rm tools/firmware-utils/patches/002-tplink-safeloader-Add-support-for-Mercusys-MR70X.patch
vi tools/firmware-utils/Makefile    # Update to latest firmware-utils /openwrt-22.03 commit
git commit

git checkout openwrt-23.05
git rm tools/firmware-utils/patches/001-add-sifiveu-guid-types.patch
vi tools/firmware-utils/Makefile    # Update to latest firmware-utils /openwrt-23.05 commit
git commit

git checkout main
git rm tools/firmware-utils/patches/001-add-sifiveu-guid-types.patch
vi tools/firmware-utils/Makefile    # Update to latest firmware-utils /master commit
git commit
```

**Comment by svanheule** [comment]
We now have a maintenance branch for openwrt-23.05. I've included the SiFive patch and updated openwrt-23.05 to point to it.

For 22.03, I think users could also use 23.05 as latest stable release for new devices. So I wouldn't change the situation there, unless there are other changes that require an update.

**Comment by blocktrron** [comment]
@svanheule I see no issue in creating a maintenance branch for this repo to reference in 22.03. Do you stil lthink it would be beneficial?

**Comment by svanheule** [comment]
I certainly don't see any harm in creating a 22.03 branch either. It would make things more consistent, but mostly I wanted to avoid the churn as long as it wasn't necessary. Feel free to go ahead and move the patches from openwrt-22.03 to a new branch here.
