### ISSUE TITLE
Archer Ax23 V1.2 Wrong firmware version after revert to stock

### ISSUE THREAD

**Issue by smakib73** [openwrt/firmware-utils#27]
Sir...I downloaded 1.1.0 Stock firmware for tplink ax23 v1.2. but after sysupgrade done firmware version shows 3.0.3😭 also its showing my previous setting...I tried to reset the router unfortunately Reset is not working...
when i am in stock firmware the firmware version was 1.1.0

but In this tool you write there 3.0.3😭😭😭😭 Please sir fix this problem please...

I want to go back stock firmware sir please help me sir...

Only you can help me sir please 

Sir please edit this firmware version to 1.0.0
Because after reverting to stock firmware we need to update the firmware once...otherwise there is some bug after revert...such as can't reset the router..🙏🙏🙏🙏 please sir

**Comment by smakib73** [comment]
![IMG_20240516_223448](https://github.com/openwrt/firmware-utils/assets/56859962/02085c87-fce3-4df6-8f80-daae17351a76)
![Uploading IMG_20240516_223456.jpg…]()

**Comment by smakib73** [comment]
Sir please edit this firmware version to 1.0.0
Because after reverting to stock firmware we need to update the firmware once...otherwise there is some bug after revert...such as can't reset the router..🙏🙏🙏🙏 please sir

**Comment by svanheule** [comment]
Having to inconsistent version numbers after reverting back from OpenWrt is pretty standard behavior for safeloader devices. This is not considered a bug and in any case is not in the scope of the OpenWrt sysupgrade process used to revert back to stock.

The only thing that's a bit strange is that v3.0.3 (see commit a2c80c586b81efc1662fec23202b88e2790e305e) was chosen for OpenWrt, because TP-Link doesn't provide any images with that version. But if this doesn't prevent you from installing an original FW image over it to fix the version number, I don't see any reason to change this.

**Comment by smakib73** [comment]
Sir i can't install firmware after revert to stock...
because the version number is 3.0.3

but tp link letest firmware number is 1.1.0

so when i revert its showing 3.0.3 thats why i can't update
firmware..because tp link mot allow downgrade firmware..
please edit this firmware number to 1.0.0 For ax23 v1.2

**Comment by crackedpotato007** [comment]
> Having to inconsistent version numbers after reverting back from OpenWrt is pretty standard behavior for safeloader devices. This is not considered a bug and in any case is not in the scope of the OpenWrt sysupgrade process used to revert back to stock.
> 
> The only thing that's a bit strange is that v3.0.3 (see commit [a2c80c5](https://github.com/openwrt/firmware-utils/commit/a2c80c586b81efc1662fec23202b88e2790e305e)) was chosen for OpenWrt, because TP-Link doesn't provide any images with that version. But if this doesn't prevent you from installing an original FW image over it to fix the version number, I don't see any reason to change this.

The issue is, atleast from what I have observed from the thread about this issue on the forums. Since 3.0.3 is greater than stock tp link, it's impossible to flash stock firmware over stock firmware.

**Comment by crackedpotato007** [comment]
Can we reopen this, please?

**Comment by svanheule** [comment]
Changing the FW version in OpenWrt to 1.1.0 wouldn't allow installing OpenWrt any more, and any higher version would also prevent installing stock over stock after reverting.

A patch can always be submitted if there is specific problematic behavior (resetting settings?) in stock FW that can be solved with a lower version number (for example 1.9.99 or 1.1.99). It's up to device owners to modify the version number (in flash) to what verify what works and what doesn't.

**Comment by ynezz** [comment]
Maybe following would work https://forum.openwrt.org/t/online-tool-to-convert-tp-link-stock-firmwares-to-sysupgrade-compatible-images ?

**Comment by crackedpotato007** [comment]
A member in the openwrt forums has obtained the device with serial access [here](https://forum.openwrt.org/t/tp-link-ax23-wrong-firmware-version-number-after-reverting/194916/92)

If you would like something done to fix this, please let us know there.
