### ISSUE TITLE
Please sir Fix Firmware version Problem in Tplink Ax23 v1.2

### ISSUE THREAD

**Issue by smakib73** [openwrt/firmware-utils#28]
Sir please please please fix the problem in Tplink ax23 v1.2

its showing version 3.0.3 after reverting...
but i downloaded 1.1.0 version...
also reset is not working after reverting..

when i am in stock firmware its 1.1.0

please fix the wrong version number in your tool...please sir please🙏🙏🙏🙏🙏🙏😭😭😭😭😭😭😭😭😭

**Comment by svanheule** [comment]
Please don't open duplicate issues. (issue #27)
