### ISSUE TITLE
Sir Cant update firmware after revert to stock in Tplink Ax23 v1.2

### ISSUE THREAD

**Issue by smakib73** [openwrt/firmware-utils#29]
Sir i can't install firmware after revert to stock...
because the version number is 3.0.3

but tp link letest firmware number is 1.1.0

so when i revert its showing 3.0.3 thats why i can't update firmware..because tp link mot allow downgrade firmware..
please edit this firmware number to 1.0.0 For ax23 v1.2

**Comment by smakib73** [comment]
many people facing this issue....we can't update the firmware after reverting to stock...

there is no version of 3.0.3
If you edit this version number to 1.0.0 
then we will update 1.1.0 firmware after revert to stock firmware..
only you can help us...sir please

**Comment by rmilecki** [comment]
#27 #28
